org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.249
loader_version_range=[4,)

mod_id=shamanicmounts
mod_name=Shamanic Mounts
mod_license=MIT
mod_group_id=tk.darrow.shamanicmounts
mod_version=0.1.3
mod_authors=Ahmi Darrow
mod_description=Ten spirit mounts. Brace to tame, breed any two, and chase the chimera. The foal is one animal, and each ridden gift is its own gene.
